baseurl: /Grimpo
url: "juxxon23.github.io"

plugins:
      - jekyll-feed
      - jekyll-sitemap
      - jekyll-seo-tag

defaults:
    - scope:
        path: ""
      values:
          layout: "default"
