baseurl: /Grimpo
url: "grimpoteuthis-314.github.io"

plugins:
      - jekyll-feed
      - jekyll-sitemap
      - jekyll-seo-tag

markdown: kramdown

defaults:
    - scope:
        path: ""
      values:
          layout: "default"

collections:
  authors:
    output: true
  topics:
    output: true
